import { MapAttribute, MapName } from '../enums'

export const NameMap = {
  [MapName.AQUADOME]: 'Aquadome',
  [MapName.BECKWITH_PARK]: 'Beckwith Park',
  [MapName.CHAMPIONS_FIELD]: 'Champions Field',
  [MapName.CORE_707]: 'Core 707',
  [MapName.CORRIDOR]: 'Corridor',
  [MapName.COSMIC]: 'Cosmic',
  [MapName.DFH_STADIUM]: 'DFH Stadium',
  [MapName.DOUBLE_GOAL]: 'Double Goal',
  [MapName.DUNK_HOUSE]: 'Dunk House',
  [MapName.FARMSTEAD]: 'Farmstead',
  [MapName.FORBIDDEN_TEMPLE]: 'Forbidden Temple',
  [MapName.MANNFIELD]: 'Mannfield',
  [MapName.NEO_TOKYO]: 'Neo Tokyo',
  [MapName.NEON_FIELDS]: 'Neon Fields',
  [MapName.OCTAGON]: 'Octagon',
  [MapName.PILLARS]: 'Pillars',
  [MapName.RIVALS_ARENA]: 'Rivals Arena',
  [MapName.SALTY_SHORES]: 'Salty Shores',
  [MapName.STARBASE_ARC]: 'Starbase Arc',
  [MapName.THROWBACK_STADIUM]: 'Throwback Stadium',
  [MapName.UNDERPASS]: 'Underpass',
  [MapName.URBAN_CENTRAL]: 'Urban Central',
  [MapName.UTOPIA_COLISEUM]: 'Utopia Coliseum',
  [MapName.UTOPIA_RETRO]: 'Utopia Retro',
  [MapName.WASTELAND]: 'Wasteland',
} as const

export const AttributeMap = {
  [MapAttribute.STANDARD]: 'Standard',
  [MapAttribute.DAY]: 'Day',
  [MapAttribute.DAWN]: 'Dawn',
  [MapAttribute.DUSK]: 'Dusk',
  [MapAttribute.NIGHT]: 'Night',
  [MapAttribute.MIDNIGHT]: 'Midnight',
  [MapAttribute.SNOWY]: 'Snowy',
  [MapAttribute.STORMY]: 'Stormy',
  [MapAttribute.HAUNTED]: 'Haunted',
  [MapAttribute.CIRCUIT]: 'Circuit',
  [MapAttribute.NFL]: 'NFL',
  [MapAttribute.THE_UPSIDE_DOWN]: 'The Upside Down',
  [MapAttribute.VOLLEY]: 'Volley',
} as const

const createId = (baseMap: MapName, ...attributes: MapAttribute[]) => {
  return [baseMap, ...attributes].join('.')
}

const Map = {
  ARC_P: createId(MapName.STARBASE_ARC),
  ARC_STANDARD_P: createId(MapName.STARBASE_ARC, MapAttribute.STANDARD),
  BB_P: createId(MapName.CHAMPIONS_FIELD, MapAttribute.NFL),
  BEACH_NIGHT_P: createId(MapName.SALTY_SHORES, MapAttribute.NIGHT),
  BEACH_P: createId(MapName.SALTY_SHORES),
  BEACHVOLLEY: createId(MapName.SALTY_SHORES, MapAttribute.VOLLEY),
  CHN_STADIUM_DAY_P: createId(MapName.FORBIDDEN_TEMPLE, MapAttribute.DAY),
  CHN_STADIUM_P: createId(MapName.FORBIDDEN_TEMPLE),
  CS_DAY_P: createId(MapName.CHAMPIONS_FIELD, MapAttribute.DAY),
  CS_HW_P: createId(MapName.RIVALS_ARENA),
  CS_P: createId(MapName.CHAMPIONS_FIELD),
  EUROSTADIUM_NIGHT_P: createId(MapName.MANNFIELD, MapAttribute.NIGHT),
  EUROSTADIUM_P: createId(MapName.MANNFIELD),
  EUROSTADIUM_RAINY_P: createId(MapName.MANNFIELD, MapAttribute.STORMY),
  EUROSTADIUM_SNOWNIGHT_P: createId(MapName.MANNFIELD, MapAttribute.SNOWY),
  FARM_NIGHT_P: createId(MapName.FARMSTEAD, MapAttribute.NIGHT),
  FARM_P: createId(MapName.FARMSTEAD),
  FARM_UPSIDEDOWN_P: createId(MapName.FARMSTEAD, MapAttribute.THE_UPSIDE_DOWN),
  HAUNTED_TRAINSTATION_P: createId(MapName.URBAN_CENTRAL, MapAttribute.HAUNTED),
  HOOPSSTADIUM_P: createId(MapName.DUNK_HOUSE),
  LABS_CIRCLEPILLARS_P: createId(MapName.PILLARS),
  LABS_CORRIDOR_P: createId(MapName.CORRIDOR),
  LABS_COSMIC_P: createId(MapName.COSMIC),
  LABS_COSMIC_V4_P: createId(MapName.COSMIC),
  LABS_DOUBLEGOAL_P: createId(MapName.DOUBLE_GOAL),
  LABS_DOUBLEGOAL_V2_P: createId(MapName.DOUBLE_GOAL),
  LABS_OCTAGON_02_P: createId(MapName.OCTAGON),
  LABS_OCTAGON_P: createId(MapName.OCTAGON),
  LABS_UNDERPASS_P: createId(MapName.UNDERPASS),
  LABS_UNDERPASS_V0_P: createId(MapName.UNDERPASS),
  LABS_UTOPIA_P: createId(MapName.UTOPIA_RETRO),
  MUSIC_P: createId(MapName.NEON_FIELDS),
  NEOTOKYO_P: createId(MapName.NEO_TOKYO),
  NEOTOKYO_STANDARD_P: createId(MapName.NEO_TOKYO, MapAttribute.STANDARD),
  PARK_NIGHT_P: createId(MapName.BECKWITH_PARK, MapAttribute.MIDNIGHT),
  PARK_P: createId(MapName.BECKWITH_PARK),
  PARK_RAINY_P: createId(MapName.BECKWITH_PARK, MapAttribute.STORMY),
  SHATTERSHOT_P: createId(MapName.CORE_707),
  STADIUM_DAY_P: createId(MapName.DFH_STADIUM, MapAttribute.DAY),
  STADIUM_FOGGY_P: createId(MapName.DFH_STADIUM, MapAttribute.STORMY),
  STADIUM_P: createId(MapName.DFH_STADIUM),
  STADIUM_RACE_DAY_P: createId(MapName.DFH_STADIUM, MapAttribute.CIRCUIT),
  STADIUM_WINTER_P: createId(MapName.DFH_STADIUM, MapAttribute.SNOWY),
  THROWBACKSTADIUM_P: createId(MapName.THROWBACK_STADIUM),
  TRAINSTATION_DAWN_P: createId(MapName.URBAN_CENTRAL, MapAttribute.DAWN),
  TRAINSTATION_NIGHT_P: createId(MapName.URBAN_CENTRAL, MapAttribute.NIGHT),
  TRAINSTATION_P: createId(MapName.URBAN_CENTRAL),
  UNDERWATER_P: createId(MapName.AQUADOME),
  UTOPIASTADIUM_DUSK_P: createId(MapName.UTOPIA_COLISEUM, MapAttribute.DUSK),
  UTOPIASTADIUM_P: createId(MapName.UTOPIA_COLISEUM),
  UTOPIASTADIUM_SNOW_P: createId(MapName.UTOPIA_COLISEUM, MapAttribute.SNOWY),
  WASTELAND_NIGHT_P: createId(MapName.WASTELAND, MapAttribute.NIGHT),
  WASTELAND_NIGHT_S_P: createId(
    MapName.WASTELAND,
    MapAttribute.STANDARD,
    MapAttribute.NIGHT
  ),
  WASTELAND_P: createId(MapName.WASTELAND),
  WASTELAND_S_P: createId(MapName.WASTELAND, MapAttribute.STANDARD),
}

export default Map
